#!/usr/bin/env python3
"""
Validate timing model output against analytical reference statistics.

Runs the simulator on each test ELF with --json, then compares key fields
against the reference JSON files generated by analyze_elf.py.

Usage:
    python3 validate.py [--filter PATTERN] [--timeout SECS]
"""

import argparse
import json
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "..", ".."))
SIM = os.path.join(PROJECT_ROOT, "build", "runner", "gpu_sim")
ISA_ELF_DIR = os.path.join(PROJECT_ROOT, "tests", "riscv-isa", "build")
ISA_REF_DIR = os.path.join(SCRIPT_DIR, "..", "isa")

# Fields to compare between simulator output and reference
COMPARE_FIELDS = [
    "total_cycles",
    "total_instructions_issued",
    "branch_flushes",
    "alu_instructions",
    "mul_instructions",
    "div_instructions",
    "ldst_instructions",
    "cache_hits",
    "cache_misses",
    "load_hits",
    "load_misses",
    "store_hits",
    "store_misses",
    "coalesced_requests",
    "serialized_requests",
    "external_memory_reads",
    "external_memory_writes",
]


def run_simulator(elf_path: str, timeout_sec: int) -> dict | None:
    """Run the simulator and return parsed JSON output, or None on failure."""
    try:
        result = subprocess.run(
            [SIM, elf_path, "--num-warps=1", "--json"],
            capture_output=True, text=True, timeout=timeout_sec
        )
        if result.returncode != 0:
            return None
        return json.loads(result.stdout)
    except (subprocess.TimeoutExpired, json.JSONDecodeError, FileNotFoundError):
        return None


def compare(sim_data: dict, ref_data: dict) -> tuple[bool, list[str]]:
    """Compare simulator output against reference. Returns (passed, details)."""
    expected = ref_data["expected_stats"]
    mismatches = []

    for field in COMPARE_FIELDS:
        sim_val = sim_data.get(field, "MISSING")
        ref_val = expected.get(field, "MISSING")
        if sim_val != ref_val:
            mismatches.append(f"    {field}: sim={sim_val} ref={ref_val}")

    return len(mismatches) == 0, mismatches


def main():
    parser = argparse.ArgumentParser(description="Validate timing model against references")
    parser.add_argument("--filter", default="", help="Only run tests matching PATTERN")
    parser.add_argument("--timeout", type=int, default=15, help="Timeout per test in seconds")
    args = parser.parse_args()

    if not os.path.isfile(SIM):
        print(f"Error: simulator not found at {SIM}")
        print("Build with: cmake -B build && cmake --build build -j8")
        sys.exit(1)

    pass_count = 0
    fail_count = 0
    skip_count = 0
    failed_tests = []

    print("=== Performance Reference Validation ===")
    print(f"Simulator: {SIM}")
    print(f"Timeout: {args.timeout}s per test")
    print()

    # --- ISA Tests ---
    print("--- ISA Tests ---")
    ref_files = sorted(
        f for f in os.listdir(ISA_REF_DIR)
        if f.endswith(".json")
    )

    for ref_filename in ref_files:
        test_name = ref_filename.replace(".json", "")

        if args.filter and args.filter not in test_name:
            continue

        elf_path = os.path.join(ISA_ELF_DIR, test_name)
        ref_path = os.path.join(ISA_REF_DIR, ref_filename)

        if not os.path.isfile(elf_path):
            print(f"SKIP {test_name} (ELF not found)")
            skip_count += 1
            continue

        # Load reference
        with open(ref_path) as f:
            ref_data = json.load(f)

        # Run simulator
        sim_data = run_simulator(elf_path, args.timeout)
        if sim_data is None:
            print(f"SKIP {test_name} (timeout or error)")
            skip_count += 1
            continue

        # Compare
        passed, details = compare(sim_data, ref_data)
        if passed:
            print(f"PASS {test_name}")
            pass_count += 1
        else:
            print(f"FAIL {test_name}")
            for line in details:
                print(line)
            fail_count += 1
            failed_tests.append(test_name)

    print()
    print("=== Summary ===")
    print(f"  PASS: {pass_count}")
    print(f"  FAIL: {fail_count}")
    print(f"  SKIP: {skip_count}")

    if failed_tests:
        print(f"\nFailed tests:")
        for t in failed_tests:
            print(f"  {t}")
        sys.exit(1)
    elif pass_count == 0:
        print("\nWarning: no tests passed")
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
