#!/usr/bin/env python3
"""Lint cross-stage accessor naming in the timing model.

Scans every header under `sim/include/gpu_sim/timing/` and reports
violations of the rules documented in
`/resources/cpp_coding_standard.md` § Cross-stage accessor naming and
`/resources/timing_discipline.md`.

Seven checks run in order. The first six are header-checks; the seventh
is a libclang-driven static-analysis pass over the `.cpp` translation
units.

The two state-shape rules introduced with the `reg.h` migration (final
phase of `project-plans/shiny-meandering-pine.md`):

  *No raw current_/next_ field pair* — if a class declares both
  `current_<NAME>_` and `next_<NAME>_` as member fields, the lint
  rejects the pair and points at the canonical primitives in
  `sim/include/gpu_sim/timing/reg.h`. Lone `next_<NAME>_` (e.g.
  `LdStUnit::next_push_` documented staging slot, `MSHREntry::next_in_chain`
  struct link) and lone `current_<NAME>_` are intentionally legal.

  *Every Reg<>/RegFifo<> member must be enrolled* — every
  `Reg<>` / `RegFifo<>` member of a `RegisteredStage`-derived class
  must appear in a `register_state(&<NAME>, ...)` call (in the header's
  inline constructor body OR the corresponding `.cpp` constructor). A
  Reg/RegFifo member whose owning class does NOT derive
  `RegisteredStage` is also flagged (the mixin is mandatory for
  registers). `Wire<>` is exempt: a `Wire` is not a `RegBase`, has no
  committed twin, and is reset/driven inline by its producer.

  *Prefix layer* — every public const member function returning `bool`,
  `std::optional<…>`, a payload struct, or a payload reference must
  start with `current_` or `next_`. Lifecycle hooks (`evaluate`,
  `commit`, `reset`, `flush`, `seed_next`, `accept`, `consume_result`,
  `add_source`, etc.) are exempt via the explicit `LIFECYCLE_METHODS`
  allowlist.

  *Postfix layer* — for each accessor, classify by return type and name
  shape:
    - `bool` and matches `^(current|next)_has_<noun>` → possession
      predicate, OK.
    - `bool` otherwise → expected state predicate; flag any `_is_*` /
      `_has_*` mid-name patterns that suggest the wrong shape.
    - non-`bool` → expected payload accessor; flag adjective tells
      (`_busy`, `_idle`, `_stalled`, `_full`, `_empty`).

  *Polarity layer* — flag pairs of accessors on the same class whose
  names suggest inverse meanings (`busy`/`ready`, `stalled`/`advancing`,
  `full`/`empty` etc.). Only one polarity per concept.

  *Field-shape layer* — fields named `current_*` / `next_*` must be
  declared in a `private:` section. Public bare references to other
  module classes held as members are flagged as candidates for the
  post-wired-pointer rule (human decides).

  *Cross-module-read layer* (Phase 10F) — a libclang pass over the
  timing `.cpp` translation units. It finds every cross-module
  `other->next_*()` member-call read and classifies it by dataflow
  direction against the shared `MODULE_ORDER`:

    - reader upstream of producer  → COMBINATIONAL backward → OK
      (legitimate back-pressure / stall — the expected first-class use
      of a `next_*` cross-module read).
    - reader downstream of producer → COMBINATIONAL forward → VIOLATION
      (collapses pipeline depth; after Phase 10 no such edge is
      legitimate).
    - reader == producer → self-read of an own staging field → exempt.

  There is no allowlist of legitimate back edges — direction is
  structural. Control-cluster orchestrators (`TimingModel`,
  `PanicController`) are exempt as *readers*: they observe arbitrary
  module state from orchestration methods and are not part of the
  linear pipeline dataflow. The one named exception is
  `ExternalMemoryInterface::next_has_response()`, a `next_`-prefixed
  compatibility alias that actually returns committed state — see
  `NEXT_PREFIX_COMMITTED_ALIASES`.

Initial mode is report-only (Phase 0): the script prints findings to
stdout but exits 0. Phase 6 flips the default to enforcement; the
`--report-only` flag preserves the legacy behavior for local
exploration. CI invokes the script without flags.

The cross-module-read layer requires `build/compile_commands.json`
(generated by `cmake -B build`) and the libclang Python bindings. In
default enforcement mode, inability to run this layer fails the build;
use `--report-only` for local exploration or `--skip-cross-module` for
an explicit header-only run.

Per-line annotation `// timing-naming-allow: <reason>` silences a
single finding on the annotated line.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_HEADER_DIR = REPO_ROOT / "sim" / "include" / "gpu_sim" / "timing"
DEFAULT_COMPILE_DB = REPO_ROOT / "build" / "compile_commands.json"
DEFAULT_SIM_ROOT = REPO_ROOT / "sim"

# `tools/` is on the path when run from the repo; make the sibling
# modules importable when invoked from anywhere.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from pipeline_order import (  # noqa: E402
    CONTROL_MODULES,
    MODULE_ORDER,
    module_index,
)

# `next_`-prefixed accessors that, by documented exception, return
# committed end-of-previous-cycle state rather than a live mid-tick
# transient — so a cross-module read of them is NOT a combinational
# edge regardless of dataflow direction. The cross-module-read layer
# skips these with an explicit note.
#
#   ExternalMemoryInterface::next_has_response() is a Phase-M5
#   compatibility alias for current_has_response(). The cache reads it
#   at the top of cache.evaluate(), before mem_if.evaluate() produces
#   this cycle's responses, so it is already a committed-state read.
#   The MODULE_ORDER rule would classify the read as "backward / OK"
#   for the wrong reason (it is not a back-pressure signal at all); the
#   alias is exempted explicitly instead of being silently accepted.
#   Documented in resources/timing_discipline.md row 15 and
#   resources/perf_sim_arch.md.
NEXT_PREFIX_COMMITTED_ALIASES: dict[str, str] = {
    "next_has_response": (
        "ExternalMemoryInterface::next_has_response() is a Phase-M5 "
        "compatibility alias that returns committed state "
        "(current_has_response()); not a combinational edge"
    ),
}

# Concrete classes that the unit hierarchy collapses to a single
# MODULE_ORDER position. A read through an `ExternalMemoryInterface*`
# resolves to the abstract base; its concrete backends share the base's
# dataflow slot. Likewise the gather-buffer source wrapper.
MODULE_NAME_REWRITE: dict[str, str] = {
    "FixedLatencyMemory":    "ExternalMemoryInterface",
    "DRAMSim3Memory":        "ExternalMemoryInterface",
    "QueuedWritebackSource": "LoadGatherBufferFile",
}

# Classes the lint inspects. Other classes/structs declared in the
# timing/ headers (data POD structs, helper buffers like MSHRFile and
# InstructionBuffer, branch predictor) are out of scope for the
# cross-stage accessor convention. Listed explicitly so a new module
# entering the diagram has to be added here too — keeps the lint and
# the diagram extractor in sync.
TIMING_MODULES: set[str] = {
    "FetchStage",
    "DecodeStage",
    "WarpScheduler",
    "Scoreboard",
    "BranchShadowTracker",
    "OperandCollector",
    "ALUUnit",
    "MultiplyUnit",
    "DivideUnit",
    "TLookupUnit",
    "LdStUnit",
    "CoalescingUnit",
    "LoadGatherBufferFile",
    "L1Cache",
    "ExternalMemoryInterface",
    "FixedLatencyMemory",
    "DRAMSim3Memory",
    "WritebackArbiter",
    "PanicController",
    "TimingModel",
    "PipelineStage",
    "ExecutionUnit",
    "QueuedWritebackSource",
}

# Helper buffers owned *inside* a pipeline module — not stages themselves,
# and explicitly out of scope for the cross-stage accessor convention (see
# the TIMING_MODULES doc above). A `next_*` accessor on one of these is a
# write handle into the helper's own REGISTERED double-buffer (e.g.
# `MSHRFile::next_at`), driven by the owning module's evaluate; it is an
# intra-module registered-pair write, not a cross-*stage* back-pressure
# edge, so the cross-module-read layer skips it.
#
# `Reg` / `RegFifo` (sim/include/gpu_sim/timing/reg.h) are the state
# primitives every stage's registers are built from. `Reg::next()` /
# `Reg::next_mut()` are intra-object staged accessors: a `Reg` member is
# always `private` to its owning stage, so a `<reg>.next_mut()` call is the
# stage touching its own register, never a cross-stage edge. Cross-stage
# reads still go through the *stage's* own `next_*()` accessor, whose
# declaring class resolves via MODULE_ORDER and is checked normally.
INTERNAL_HELPER_CLASSES: set[str] = {
    "MSHRFile",
    "Reg",
    "RegFifo",
}

# Methods exempt from the prefix rule. Each entry below was verified to
# suppress at least one finding on a TIMING_MODULES class — non-const
# lifecycle methods (evaluate / commit / reset / flush / accept etc.)
# don't need entries here because the prefix layer only inspects public
# const accessors, so non-const methods are skipped by construction.
# Same for private helpers (the access-tracker filters them out).
#
# Audit checklist when adding a new entry:
#   (1) Is the accessor read by another module's evaluate() / commit()
#       in a flow-control role? If yes, it IS a cross-stage signal —
#       rename it with the current_*/next_* prefix instead of allow-
#       listing.
#   (2) Does the accessor's underlying field follow the discipline
#       (`current_*` / `next_*` double-buffered)? If yes, the natural
#       name is the prefixed form; allow-listing is hiding a real miss.
#   (3) If neither — the accessor is genuinely scalar telemetry,
#       configuration, an orchestrator-status latch, or a snapshot view
#       — the entry belongs here.
LIFECYCLE_METHODS: set[str] = {
    # ───── Stat counters and capacity reporters ─────────────────────
    # These return scalars derived from internal subsystem state
    # (MSHR active count, queue depths, write-buffer occupancy,
    # configuration-driven sizes). They are consumed by tests and the
    # trace exporter, never by another module's flow-control logic.
    "active_mshr_count",
    "active_mshr_warps",
    "secondary_mshr_count",
    "pinned_line_count",
    "write_buffer_size",
    "in_flight_count",
    "response_count",
    "write_ack_count",
    "request_fifo_size",
    "max_observed_response_queue",
    "read_response_queue_capacity",
    "max_observed_write_ack_queue",
    "write_ack_queue_capacity",
    "dram_ticks",
    "chunks_per_line",
    "ready_source_count",
    "pipeline_occupancy",
    "queue_depth",
    "num_buffers",
    "cycle_count",

    # ───── Snapshot views ───────────────────────────────────────────
    # Vector / reference returns derived from committed state, used by
    # tests and the trace exporter only.
    "active_warps",
    "pipeline_snapshot",
    "mshrs",
    "buffer",

    # ───── Orchestrator state-machine status ────────────────────────
    # PanicController is a one-shot state machine — these fields are
    # set once by `trigger()` / mutated by `evaluate()` step transitions
    # and observed by TimingModel::tick(). They are not double-buffered
    # cross-stage signals; the prefix rule's premise (next_*/current_*
    # field pair) doesn't apply.
    "is_active",
    "is_done",
    "step",
    "panic_warp",
    "panic_pc",
    "panic_cause",

    # ───── Drain / aggregate-idle predicates ────────────────────────
    # Distinct from the back-pressure `current_busy()` signal: an idle
    # subsystem is fully drained (no work in any stage), whereas a
    # busy/stalled module is rejecting *new* work this cycle. The two
    # are not inverses, so allow-listing the drain check does not
    # collide with the polarity rule.
    "is_idle",
    "is_coalesced",  # CoalescingUnit per-cycle FSM state, post-commit query

    # ───── Per-unit snapshot accessors ──────────────────────────────
    # Each unit exposes `busy()` / `active_warp()` / `pending_input()`
    # / `pending_entry()` / `result_entry()` for `build_cycle_snapshot`
    # and the structured trace. These read committed (`current_*`)
    # state, but a cross-stage flow-control consumer reads the
    # `current_busy()` back-pressure signal instead — so these names
    # don't clash with the discipline at any cross-stage call site.
    "busy",
    "active_warp",
    "resident_warp",
    "pending_input",
    "pending_entry",
    "result_entry",
    "serial_index",         # CoalescingUnit per-cycle counter snapshot
}

# Words that indicate a state predicate when seen as a standalone or
# trailing token — used by the postfix layer to flag adjectives in
# payload-accessor names.
ADJECTIVE_TELLS: set[str] = {
    "busy",
    "idle",
    "stalled",
    "full",
    "empty",
    "ready",
    "active",
    "pending",
    "claimed",
}

# Inverse-polarity word pairs flagged by the polarity layer.
INVERSE_PAIRS: list[tuple[str, str]] = [
    ("busy", "ready"),
    ("busy", "free"),
    ("busy", "idle"),
    ("stalled", "advancing"),
    ("stalled", "ready"),
    ("full", "empty"),
    ("active", "idle"),
    ("pending", "ready"),
]

ALLOW_ANNOTATION_RE = re.compile(r"//\s*timing-naming-allow:")


@dataclass
class Finding:
    file: Path
    line: int
    rule: str
    message: str

    def format(self, root: Path) -> str:
        try:
            rel = self.file.relative_to(root)
        except ValueError:
            rel = self.file
        return f"{rel}:{self.line}: [{self.rule}] {self.message}"


@dataclass
class ClassInfo:
    name: str
    start_line: int
    methods: list[tuple[str, int, str, str]] = field(default_factory=list)
    # (name, line, return_type, access)
    fields: list[tuple[str, int, str, str]] = field(default_factory=list)
    # (name, line, type, access)
    bases: list[str] = field(default_factory=list)
    # base class names captured from the class header line


# Regex to capture a public const accessor's signature. Captures:
#   1: return type (rough, may include `const`, `&`, `*`, template args)
#   2: method name
PUBLIC_CONST_METHOD_RE = re.compile(
    r"""^\s*
        (?:virtual\s+)?
        (?:static\s+)?
        (?:inline\s+)?
        (?P<ret>
            (?:const\s+)?
            [A-Za-z_:][\w:<>,\s\*&]*?
        )
        \s+
        (?P<name>[A-Za-z_]\w*)
        \s*\(
        (?P<args>[^)]*)
        \)
        \s*const
        \s*(?:override)?
        \s*(?:=\s*(?:0|default))?
        \s*[;{]
    """,
    re.VERBOSE,
)

# Regex to capture a member field declaration. Captures:
#   1: type
#   2: name
FIELD_RE = re.compile(
    r"""^\s*
        (?P<type>
            (?:const\s+|static\s+|mutable\s+)*
            [A-Za-z_:][\w:<>,\s\*&]*?
        )
        \s+
        (?P<name>[A-Za-z_]\w*)
        \s*(?:=\s*[^;]+)?
        \s*[;{]
    """,
    re.VERBOSE,
)

# Class/struct opener. Captures the class name; the caller filters out
# forward declarations (`class Foo;` — no `{` or inheritance `:`) so
# they don't shadow the real definition that follows.
CLASS_OPEN_RE = re.compile(r"^\s*(?:class|struct)\s+([A-Za-z_]\w*)\b")

# Inheritance list parse: captures the base names from a class header
# line (`class Foo : public Bar, protected Baz {`). We tolerate
# trailing `{` or end-of-line (multi-line inheritance list).
INHERITANCE_RE = re.compile(
    r":\s*((?:(?:public|protected|private|virtual)\s+)*"
    r"[A-Za-z_:][\w:]*"
    r"(?:\s*,\s*(?:(?:public|protected|private|virtual)\s+)*"
    r"[A-Za-z_:][\w:]*)*)"
)


def _extract_bases(header_line: str) -> list[str]:
    """Return the base class names listed on a class header line.

    Strips access-specifier keywords (`public`, `protected`, `private`,
    `virtual`) and namespace qualifications, leaving just the leaf
    type name (`RegisteredStage` from `public gpu_sim::RegisteredStage`).
    """
    m = INHERITANCE_RE.search(header_line)
    if not m:
        return []
    bases: list[str] = []
    for chunk in m.group(1).split(","):
        chunk = chunk.strip()
        # Strip leading access / virtual keywords.
        chunk = re.sub(
            r"^(?:(?:public|protected|private|virtual)\s+)+", "", chunk
        )
        # Strip namespace qualification.
        chunk = chunk.split("::")[-1]
        if chunk:
            bases.append(chunk)
    return bases


def _strip_comments(text: str) -> str:
    """Strip // and /* */ comments to reduce false matches in regex."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def _parse_header(path: Path) -> list[ClassInfo]:
    """Parse a header into ClassInfo records.

    Light-touch: tracks brace depth to find class boundaries and
    public/private/protected sections. Skips non-module classes.
    """
    classes: list[ClassInfo] = []
    text = path.read_text()
    lines = text.splitlines()

    # Map line → access section by walking with a brace counter.
    cls: ClassInfo | None = None
    cls_brace_open: int | None = None
    brace_depth = 0
    access = "private"  # default for class; we'll override on entry

    i = 0
    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()
        # Skip preprocessor and pure comment lines for class detection.
        compact = _strip_comments(raw)

        # Track class entry. Skip pure forward declarations
        # (`class Foo;`) — they have no `{` and no inheritance `:` on the
        # line and would otherwise shadow the real definition that
        # follows in the same header (e.g. `class WritebackArbiter;`
        # at the top of alu_unit.h before `class ALUUnit { ... };`).
        #
        # We parse ALL classes (not only TIMING_MODULES) so the
        # state-shape checks can inspect Reg-bearing helper classes
        # like MSHRFile. The existing prefix/postfix/polarity/field-
        # shape checks filter by TIMING_MODULES on their own.
        if cls is None:
            m = CLASS_OPEN_RE.match(compact)
            if m:
                is_forward_decl = ("{" not in compact
                                   and ":" not in compact
                                   and compact.rstrip().endswith(";"))
                if not is_forward_decl:
                    cls = ClassInfo(name=m.group(1), start_line=i + 1)
                    cls_brace_open = None
                    # Default access depends on keyword.
                    kw = compact.split()[0]
                    access = "public" if kw == "struct" else "private"
                    # Capture base classes — header line may continue
                    # onto subsequent lines until the opening brace, so
                    # join until we see `{`.
                    header_chunk = compact
                    j = i
                    while "{" not in header_chunk and j + 1 < len(lines):
                        j += 1
                        header_chunk += " " + _strip_comments(lines[j])
                    cls.bases = _extract_bases(header_chunk)
        # Track brace depth & access transitions inside an open class.
        if cls is not None:
            opens = compact.count("{")
            closes = compact.count("}")
            if cls_brace_open is None and opens > 0:
                cls_brace_open = brace_depth + 1
            brace_depth_before = brace_depth
            brace_depth += opens - closes

            if cls_brace_open is not None:
                # access transition lines like "public:" / "private:" /
                # "protected:" that appear at the class scope (depth ==
                # cls_brace_open).
                if (brace_depth == cls_brace_open
                        and brace_depth_before == cls_brace_open):
                    label_match = re.match(
                        r"^\s*(public|private|protected)\s*:", compact)
                    if label_match:
                        access = label_match.group(1)

                # Member detection: any line that *starts* at class scope
                # (brace_depth_before == cls_brace_open) is a candidate
                # member declaration. We match regardless of whether the
                # line opens a brace — multi-line inline method
                # definitions ("ReturnT name() const { ... }" split
                # across several lines) start at class scope and open a
                # brace, but the signature is fully on the opening line.
                if brace_depth_before == cls_brace_open:
                    method_match = PUBLIC_CONST_METHOD_RE.match(compact)
                    if method_match and access == "public":
                        ret = method_match.group("ret").strip()
                        name = method_match.group("name")
                        cls.methods.append(
                            (name, i + 1, ret, access)
                        )
                    elif brace_depth == cls_brace_open:
                        # Field declaration heuristic: only recognize
                        # lines that don't change brace depth (so we
                        # don't mistake a method body opener for a
                        # field), end with `;`, and aren't
                        # function-shaped (no `(` outside template
                        # args).
                        if (";" in compact and "(" not in compact
                                and "operator" not in compact):
                            fm = FIELD_RE.match(compact)
                            if fm:
                                name = fm.group("name")
                                type_ = fm.group("type").strip()
                                if name not in ("public", "private", "protected"):
                                    cls.fields.append(
                                        (name, i + 1, type_, access)
                                    )

                # Class close.
                if brace_depth < cls_brace_open:
                    classes.append(cls)
                    cls = None
                    cls_brace_open = None
                    access = "private"
        i += 1
    return classes


def _is_payload_return(ret: str) -> bool:
    """Return True if the return type is non-bool (a payload type)."""
    ret_clean = ret.replace("override", "").strip()
    # Strip leading const/virtual/static.
    return not re.search(r"\bbool\b\s*$", ret_clean) and not ret_clean.endswith("bool")


def _allowed_on_line(line_text: str) -> bool:
    return bool(ALLOW_ANNOTATION_RE.search(line_text))


def _check_prefix(cls: ClassInfo, header: list[str], path: Path,
                  findings: list[Finding]) -> None:
    """Prefix layer: public const accessors must start with current_ or next_."""
    for (name, line, ret, access) in cls.methods:
        if access != "public":
            continue
        if name in LIFECYCLE_METHODS:
            continue
        if name.startswith("set_") or name.startswith("get_"):
            continue
        if _allowed_on_line(header[line - 1]):
            continue
        if not (name.startswith("current_") or name.startswith("next_")):
            findings.append(Finding(
                file=path, line=line, rule="prefix",
                message=(
                    f"{cls.name}::{name}() — public const accessor missing "
                    f"current_/next_ prefix; cycle discipline must be "
                    f"encoded in the name (REGISTERED → current_*, "
                    f"COMBINATIONAL → next_*)"
                ),
            ))


def _check_postfix(cls: ClassInfo, header: list[str], path: Path,
                   findings: list[Finding]) -> None:
    """Postfix layer: state predicates avoid is_/has_ filler; payload
    accessors avoid adjective tells."""
    for (name, line, ret, access) in cls.methods:
        if access != "public":
            continue
        if name in LIFECYCLE_METHODS:
            continue
        if not (name.startswith("current_") or name.startswith("next_")):
            continue
        if _allowed_on_line(header[line - 1]):
            continue
        is_payload = _is_payload_return(ret)
        body = name.split("_", 1)[1] if "_" in name else ""
        # Possession predicate?
        if body.startswith("has_"):
            if is_payload:
                findings.append(Finding(
                    file=path, line=line, rule="postfix",
                    message=(
                        f"{cls.name}::{name}() — has_<noun> form must "
                        f"return bool, but returns '{ret}'"
                    ),
                ))
            continue
        # Bool state predicate.
        if not is_payload:
            if "is_" in body:
                findings.append(Finding(
                    file=path, line=line, rule="postfix",
                    message=(
                        f"{cls.name}::{name}() — state predicate must "
                        f"use bare adjective (drop is_ filler)"
                    ),
                ))
            continue
        # Payload accessor.
        # Flag adjective tells in trailing word.
        tail = body.rsplit("_", 1)[-1] if body else ""
        if tail in ADJECTIVE_TELLS:
            findings.append(Finding(
                file=path, line=line, rule="postfix",
                message=(
                    f"{cls.name}::{name}() — payload accessor name ends "
                    f"in adjective '{tail}'; payload accessors should "
                    f"use a bare noun"
                ),
            ))


def _check_polarity(cls: ClassInfo, header: list[str], path: Path,
                    findings: list[Finding]) -> None:
    """Polarity layer: flag inverse pairs on the same class."""
    method_names = {name for (name, _line, _ret, access) in cls.methods
                    if access == "public"}
    method_lines = {name: line for (name, line, _ret, access) in cls.methods
                    if access == "public"}
    for (a, b) in INVERSE_PAIRS:
        for prefix in ("current", "next", ""):
            if prefix:
                full_a = f"{prefix}_{a}"
                full_b = f"{prefix}_{b}"
            else:
                full_a = a
                full_b = b
            if full_a in method_names and full_b in method_names:
                line_a = method_lines.get(full_a, 0)
                if _allowed_on_line(header[line_a - 1] if line_a else ""):
                    continue
                findings.append(Finding(
                    file=path, line=line_a or cls.start_line,
                    rule="polarity",
                    message=(
                        f"{cls.name} exposes inverse-polarity pair "
                        f"{full_a}() and {full_b}(); pick the "
                        f"asserted=blocking polarity and drop the other"
                    ),
                ))


def _check_field_shape(cls: ClassInfo, header: list[str], path: Path,
                       findings: list[Finding]) -> None:
    """Field-shape layer: current_*/next_* fields must be private."""
    for (name, line, type_, access) in cls.fields:
        if not (name.startswith("current_") or name.startswith("next_")):
            continue
        if _allowed_on_line(header[line - 1]):
            continue
        if access != "private":
            findings.append(Finding(
                file=path, line=line, rule="field-shape",
                message=(
                    f"{cls.name}::{name} — REGISTERED state field is "
                    f"'{access}' but must be private; expose via "
                    f"current_*()/next_*() accessor"
                ),
            ))


# Detect Reg<...> / RegFifo<...> type spellings on a field declaration.
# Matches the leading word of the field type string captured by FIELD_RE.
_REG_TYPE_RE = re.compile(r"\bReg\s*<")
_REGFIFO_TYPE_RE = re.compile(r"\bRegFifo\s*<")


def _is_reg_field(type_: str) -> bool:
    """Return True iff the field's type is a Reg<T> or RegFifo<T>."""
    return bool(_REG_TYPE_RE.search(type_) or _REGFIFO_TYPE_RE.search(type_))


def _check_no_raw_current_next_pair(
    cls: ClassInfo, header: list[str], path: Path,
    findings: list[Finding],
) -> None:
    """State-shape rule (1): raw `current_X_` / `next_X_` field pair is
    forbidden.

    If a class declares both `current_<NAME>_` and `next_<NAME>_` as
    member fields, this is the pre-`Reg<T>` hand-rolled double buffer
    that the migration replaced. Use `Reg<T>` (clock-edge register),
    `RegFifo<T>` (commit-disciplined FIFO), or `Wire<T>` (combinational
    backward signal) — see `sim/include/gpu_sim/timing/reg.h`.

    Lone `next_<NAME>_` is intentionally legal: it is the documented
    staging-slot pattern (`LdStUnit::next_push_`) or a struct chain-link
    field (`MSHREntry::next_in_chain`). Lone `current_<NAME>_` is also
    legal — no current sites in the tree, but it would be unusual rather
    than wrong.
    """
    currents: dict[str, tuple[int, str]] = {}  # base name -> (line, access)
    nexts: set[str] = set()
    for (name, line, _type, access) in cls.fields:
        if name.startswith("current_") and name.endswith("_"):
            base = name[len("current_"):-1]
            if base:
                currents[base] = (line, access)
        elif name.startswith("next_") and name.endswith("_"):
            base = name[len("next_"):-1]
            if base:
                nexts.add(base)
    for base, (line, _access) in currents.items():
        if base not in nexts:
            continue
        if _allowed_on_line(header[line - 1]):
            continue
        findings.append(Finding(
            file=path, line=line, rule="state-shape",
            message=(
                f"{cls.name}::current_{base}_ / next_{base}_ — raw "
                f"current_/next_ field pair is forbidden; use "
                f"`Reg<T> {base}_` (or `RegFifo<T>` for a commit-"
                f"disciplined FIFO, `Wire<T>` for a combinational "
                f"backward signal). See "
                f"sim/include/gpu_sim/timing/reg.h."
            ),
        ))


# Class-body `register_state(&a, &b, ...)` call. Captures the argument
# list between the parentheses; the caller pulls out the `&name`
# identifiers. We tolerate a multi-line argument list (the cache's
# `register_state(...)` spans three lines).
_REGISTER_STATE_CALL_RE = re.compile(
    r"register_state\s*\(([^;]*?)\)\s*;", re.DOTALL
)
_REGISTER_STATE_ARG_RE = re.compile(r"&\s*([A-Za-z_]\w*)")


def _collect_register_state_args(text: str) -> set[str]:
    """Return the union of `&name` identifiers from every
    `register_state(...)` call in `text`. Strips // and /* */
    comments first so a commented-out `// register_state(&foo_);`
    does not satisfy enrollment."""
    text = _strip_comments(text)
    args: set[str] = set()
    for call_match in _REGISTER_STATE_CALL_RE.finditer(text):
        for arg_match in _REGISTER_STATE_ARG_RE.finditer(call_match.group(1)):
            args.add(arg_match.group(1))
    return args


def _header_to_cpp_path(header_path: Path) -> Path | None:
    """Map a timing header path to its corresponding `.cpp` source.

    `sim/include/gpu_sim/timing/<X>.h` -> `sim/src/timing/<X>.cpp`.
    Returns `None` if the `.cpp` does not exist (header-only class).
    """
    parts = list(header_path.parts)
    try:
        idx = parts.index("include")
    except ValueError:
        return None
    # Replace `.../include/gpu_sim/timing/<X>.h` with
    # `.../src/timing/<X>.cpp`.
    if idx + 3 >= len(parts):
        return None
    if parts[idx + 1] != "gpu_sim" or parts[idx + 2] != "timing":
        return None
    new_parts = (parts[:idx] + ["src", "timing"]
                 + [parts[idx + 3].replace(".h", ".cpp")])
    cpp = Path(*new_parts)
    return cpp if cpp.exists() else None


def _check_reg_members_enrolled(
    cls: ClassInfo, header: list[str], path: Path,
    findings: list[Finding],
) -> None:
    """State-shape rule (2): every Reg<>/RegFifo<> member must be
    enrolled via `register_state(&<NAME>, ...)`.

    A class with Reg / RegFifo members MUST also derive
    `RegisteredStage` so the mixin's `seed_all()` / `commit_all()` /
    `reset_all()` loops drive them. The enrollment call may live in
    the header (inline constructor body) or in the corresponding
    `.cpp` constructor; we look at the union of both.

    `Wire<>` is NOT subject to this rule. A `Wire` is not a `RegBase`,
    has no committed twin, and is reset/driven inline by its producer
    — registering it would be a category error.
    """
    reg_fields = [
        (name, line, type_) for (name, line, type_, _access) in cls.fields
        if _is_reg_field(type_)
    ]
    if not reg_fields:
        return

    # Union of `register_state(&...)` arguments from the header and the
    # corresponding `.cpp` (if it exists). The header may carry an
    # inline constructor body (e.g. Scoreboard, MultiplyUnit); the
    # `.cpp` carries out-of-line constructor bodies.
    enrolled = _collect_register_state_args("\n".join(header))
    cpp_path = _header_to_cpp_path(path)
    if cpp_path is not None:
        enrolled |= _collect_register_state_args(cpp_path.read_text())

    derives_registered_stage = "RegisteredStage" in cls.bases

    for (name, line, type_) in reg_fields:
        if _allowed_on_line(header[line - 1]):
            continue
        if not derives_registered_stage:
            findings.append(Finding(
                file=path, line=line, rule="state-shape",
                message=(
                    f"{cls.name}::{name} — Reg<T> / RegFifo<T> member "
                    f"lives in a class that does not derive "
                    f"`RegisteredStage`; add `public RegisteredStage` "
                    f"to the class header and enroll the member via "
                    f"register_state(&{name}, ...) in the constructor "
                    f"body so seed_all() / commit_all() / reset_all() "
                    f"drive it."
                ),
            ))
            continue
        if name not in enrolled:
            findings.append(Finding(
                file=path, line=line, rule="state-shape",
                message=(
                    f"{cls.name}::{name} — Reg<T> / RegFifo<T> member "
                    f"is not enrolled via register_state(); add it to "
                    f"a register_state(&{name}, ...) call in the "
                    f"constructor body so seed_all() / commit_all() / "
                    f"reset_all() drive it."
                ),
            ))


def lint_header(path: Path) -> list[Finding]:
    """Lint a single header file and return findings."""
    findings: list[Finding] = []
    text = path.read_text()
    lines = text.splitlines()
    classes = _parse_header(path)
    for cls in classes:
        # Existing prefix/postfix/polarity/field-shape checks are
        # scoped to the pipeline-module set.
        if cls.name in TIMING_MODULES:
            _check_prefix(cls, lines, path, findings)
            _check_postfix(cls, lines, path, findings)
            _check_polarity(cls, lines, path, findings)
            _check_field_shape(cls, lines, path, findings)
        # State-shape checks (raw current_/next_ pair forbidden; every
        # Reg / RegFifo member must be enrolled via register_state)
        # apply to every class that holds state, including Reg-bearing
        # helper classes like MSHRFile.
        _check_no_raw_current_next_pair(cls, lines, path, findings)
        _check_reg_members_enrolled(cls, lines, path, findings)
    return findings


def lint_directory(header_dir: Path) -> list[Finding]:
    """Lint every .h file under `header_dir` and return findings sorted
    by (file, line)."""
    findings: list[Finding] = []
    for path in sorted(header_dir.rglob("*.h")):
        findings.extend(lint_header(path))
    findings.sort(key=lambda f: (str(f.file), f.line, f.rule))
    return findings


# ───────────────────────────────────────────────────────────────────────
# Cross-module-read layer (Phase 10F)
#
# A libclang pass over the timing `.cpp` translation units. It finds
# every cross-module `other->next_*()` member-call read and classifies
# it by dataflow direction against the shared `MODULE_ORDER`.
# ───────────────────────────────────────────────────────────────────────


def _normalize_module(name: str | None) -> str | None:
    """Collapse a concrete class spelling to its MODULE_ORDER identity.

    Concrete `ExternalMemoryInterface` backends and the gather-buffer
    source wrapper share their base's dataflow slot
    (`MODULE_NAME_REWRITE`). Returns the canonical module name, or
    `None` if `name` is not a pipeline module.
    """
    if not name:
        return None
    canonical = MODULE_NAME_REWRITE.get(name, name)
    return canonical if module_index(canonical) >= 0 else None


def _record_ancestor(cursor: "object") -> str | None:
    """Return the spelling of the class/struct that owns `cursor` as a
    member (its `semantic_parent` chain), or `None` for a free
    function.

    Used to resolve the *reader* class of a `next_*` call: the call is
    scanned from inside a `CXX_METHOD` definition cursor, and that
    method's `semantic_parent` is the enclosing class. For an
    out-of-line definition (`void FetchStage::evaluate() {...}`) the
    `semantic_parent` is still the class, so this works for both
    in-class and out-of-line method bodies.
    """
    import clang.cindex as cindex

    record_kinds = {
        cindex.CursorKind.CLASS_DECL,
        cindex.CursorKind.STRUCT_DECL,
        cindex.CursorKind.CLASS_TEMPLATE,
    }
    node = cursor.semantic_parent
    safety = 0
    while node is not None and safety < 32:
        if node.kind in record_kinds and node.spelling:
            return node.spelling
        node = node.semantic_parent
        safety += 1
    return None


def _scan_tu_for_cross_module_reads(
    tu: "object", sim_timing_dir: str, findings: list[Finding],
    seen: set[tuple[str, int, str]],
) -> None:
    """Walk one translation unit for `other->next_*()` member calls and
    append cross-module-read findings.

    The walk is *method-rooted*: it iterates `CXX_METHOD` definitions
    located under `sim/src/timing/`, then scans each method body subtree
    for `next_*` calls. The reader class is the method's owning class —
    statically known without walking expression parents. A `next_*`
    call found *outside* any method body (a free function or a
    file-scope lambda) is itself a discipline violation and is
    diagnosed.

    `seen` dedups by (file, line, callee) because the same call site
    appears once per TU that includes the source file."""
    import clang.cindex as cindex

    Kind = cindex.CursorKind

    def _is_under_timing(loc) -> bool:
        if loc.file is None:
            return False
        return os.path.abspath(loc.file.name).startswith(sim_timing_dir)

    # Collect every function-like definition under sim/src/timing/.
    func_kinds = {Kind.CXX_METHOD, Kind.FUNCTION_DECL, Kind.CONSTRUCTOR,
                  Kind.DESTRUCTOR, Kind.CONVERSION_FUNCTION}
    method_defs: list[object] = []
    for cursor in tu.cursor.walk_preorder():
        if cursor.kind in func_kinds and cursor.is_definition():
            if _is_under_timing(cursor.location):
                method_defs.append(cursor)

    for method in method_defs:
        reader_raw = _record_ancestor(method)
        for cursor in method.walk_preorder():
            if cursor.kind != Kind.CALL_EXPR:
                continue
            callee_name = cursor.spelling or ""
            if not callee_name.startswith("next_"):
                continue
            loc = cursor.location
            if not _is_under_timing(loc):
                continue
            abs_path = os.path.abspath(loc.file.name)

            ref = cursor.referenced
            if ref is None or ref.semantic_parent is None:
                key = (abs_path, loc.line, callee_name)
                if key in seen:
                    continue
                seen.add(key)
                findings.append(Finding(
                    file=Path(abs_path), line=loc.line,
                    rule="cross-module-read",
                    message=(
                        f"{callee_name}() — call receiver / declaration "
                        f"failed to resolve statically; the cross-stage "
                        f"discipline requires every `next_*` read to have "
                        f"a statically resolvable receiver class"
                    ),
                ))
                continue
            producer_raw = ref.semantic_parent.spelling

            key = (abs_path, loc.line, callee_name)
            if key in seen:
                continue
            seen.add(key)
            _classify_cross_module_read(
                abs_path, loc.line, callee_name,
                producer_raw, reader_raw, findings,
            )


def _classify_cross_module_read(
    abs_path: str, line: int, callee_name: str,
    producer_raw: str, reader_raw: str | None,
    findings: list[Finding],
) -> None:
    """Classify a single `producer_raw::callee_name()` read performed by
    `reader_raw` and append a finding iff it is a violation."""
    producer = _normalize_module(producer_raw)
    reader = _normalize_module(reader_raw)

    # A `next_*` accessor on an internal helper buffer (MSHRFile, ...) is a
    # registered-pair write handle internal to the owning pipeline module,
    # not a cross-stage edge — out of scope for this layer.
    if producer is None and producer_raw in INTERNAL_HELPER_CLASSES:
        return

    # The producer must be a known pipeline module — every `next_*`
    # accessor in the timing model lives on one. If it does not
    # resolve, the receiver resolution failed; diagnose loudly.
    if producer is None:
        findings.append(Finding(
            file=Path(abs_path), line=line, rule="cross-module-read",
            message=(
                f"{callee_name}() — declaring class {producer_raw!r} is "
                f"not a known pipeline module; receiver class failed to "
                f"resolve to a MODULE_ORDER entry"
            ),
        ))
        return

    if reader is None:
        findings.append(Finding(
            file=Path(abs_path), line=line, rule="cross-module-read",
            message=(
                f"{producer}::{callee_name}() read from a context whose "
                f"enclosing class ({reader_raw!r}) is not a pipeline "
                f"module — cross-stage `next_*` reads must occur in a "
                f"module method, not a free function or lambda"
            ),
        ))
        return

    # Self-read of an own staging field: a module reading its own
    # `next_foo()` (including via a method another module invoked,
    # where the receiver is still `this`) is internal staging.
    if reader == producer:
        return

    # Documented `next_`-prefixed committed-state alias: not a
    # combinational edge, exempt with an explicit note.
    if callee_name in NEXT_PREFIX_COMMITTED_ALIASES:
        return

    # Control-cluster orchestrators observe arbitrary module state from
    # orchestration methods (tick / record_cycle_trace /
    # PanicController::evaluate); they are not part of the linear
    # pipeline dataflow, so a read by an orchestrator is exempt.
    if reader in CONTROL_MODULES:
        return

    ri = module_index(reader)
    pi = module_index(producer)

    if ri < pi:
        # Reader upstream of producer → combinational backward →
        # legitimate back-pressure / stall.
        return

    # Reader downstream of the producer → combinational forward →
    # violation (the self-read case is already returned above).
    findings.append(Finding(
        file=Path(abs_path), line=line, rule="cross-module-read",
        message=(
            f"{reader}::… reads {producer}::{callee_name}() — "
            f"combinational *forward* edge ({reader} is downstream of "
            f"{producer} in the pipeline dataflow order). A `next_*` "
            f"cross-module read is only legitimate as a "
            f"combinational-backward back-pressure / stall signal; a "
            f"forward read collapses pipeline depth. Stage the value "
            f"through a REGISTERED current_*/next_* pair instead."
        ),
    ))


def lint_cross_module_reads(
    compile_db: Path, sim_root: Path,
) -> tuple[list[Finding], list[str]]:
    """Cross-module-read layer. Returns (findings, unavailable_notes).

    A non-empty `unavailable_notes` means the layer could not run
    (missing libclang bindings, compile DB, or parseable timing TUs).
    The caller treats that as a failure in default enforcement mode.
    """
    skip_notes: list[str] = []
    try:
        import clang.cindex  # noqa: F401
    except ImportError:
        skip_notes.append(
            "cross-module-read layer skipped: libclang Python bindings "
            "not installed (`pip install -r tools/requirements.txt`)"
        )
        return [], skip_notes

    if not compile_db.exists():
        skip_notes.append(
            f"cross-module-read layer skipped: {compile_db} not found "
            f"(run `cmake -B build` to generate it)"
        )
        return [], skip_notes

    # Reuse the AST extractor's compile-DB plumbing and TU parser so the
    # two tools resolve translation units identically.
    import diagram_extract_ast as ast_ext

    entries = ast_ext._load_compile_db(compile_db)
    timing_entries = ast_ext._select_timing_tus(entries, sim_root)
    if not timing_entries:
        skip_notes.append(
            f"cross-module-read layer skipped: no timing translation "
            f"units found under {sim_root}/src/timing"
        )
        return [], skip_notes

    try:
        tus, parse_warnings = ast_ext._parse_translation_units(timing_entries)
    except Exception as exc:
        skip_notes.append(
            "cross-module-read layer skipped: libclang failed to parse "
            f"translation units ({exc})"
        )
        return [], skip_notes
    if not tus:
        skip_notes.append(
            "cross-module-read layer skipped: no translation units parsed "
            "(check that the libclang version matches the compiler used "
            "for compile_commands.json)"
        )
        return [], skip_notes

    sim_timing_dir = str((sim_root / "src" / "timing").resolve()) + os.sep
    findings: list[Finding] = []
    seen: set[tuple[str, int, str]] = set()
    for tu in tus:
        _scan_tu_for_cross_module_reads(tu, sim_timing_dir, findings, seen)

    findings.sort(key=lambda f: (str(f.file), f.line, f.rule))
    return findings, skip_notes


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--header-dir", type=Path, default=DEFAULT_HEADER_DIR,
        help=("Directory of timing headers to scan (default: "
              "%(default)s)"),
    )
    ap.add_argument(
        "--report-only", action="store_true",
        help=("Always exit 0 regardless of findings. Useful for local "
              "exploration; CI invokes the script without this flag and "
              "treats any finding as a failure (Phase 6 enforcement)."),
    )
    ap.add_argument(
        "--compile-db", type=Path, default=DEFAULT_COMPILE_DB,
        help=("Path to compile_commands.json for the cross-module-read "
              "layer (default: %(default)s)"),
    )
    ap.add_argument(
        "--sim-root", type=Path, default=DEFAULT_SIM_ROOT,
        help="Path to the sim source root (default: %(default)s)",
    )
    ap.add_argument(
        "--skip-cross-module", action="store_true",
        help=("Skip the libclang cross-module-read layer; run only the "
              "header-naming layers."),
    )
    args = ap.parse_args(argv)

    if not args.header_dir.is_dir():
        print(f"error: header directory not found: {args.header_dir}",
              file=sys.stderr)
        return 2

    # Header-naming layers.
    findings = lint_directory(args.header_dir)
    cross_module_unavailable = False

    # Cross-module-read layer (Phase 10F).
    if args.skip_cross_module:
        print("cross-module-read layer: skipped (--skip-cross-module)")
    else:
        cm_findings, skip_notes = lint_cross_module_reads(
            args.compile_db, args.sim_root,
        )
        cross_module_unavailable = bool(skip_notes)
        for note in skip_notes:
            print(f"note: {note}", file=sys.stderr)
        findings.extend(cm_findings)
    if args.skip_cross_module:
        cross_module_unavailable = False

    findings.sort(key=lambda f: (str(f.file), f.line, f.rule))
    for f in findings:
        print(f.format(REPO_ROOT))

    if not findings and not cross_module_unavailable:
        print("lint_timing_naming: clean")
        return 0

    if args.report_only:
        print(
            f"\nlint_timing_naming: {len(findings)} finding(s)"
            f"{' plus unavailable cross-module layer' if cross_module_unavailable else ''} "
            "(report-only mode)",
            file=sys.stderr,
        )
        return 0

    if cross_module_unavailable:
        print(
            "\nlint_timing_naming: cross-module-read layer unavailable — "
            "failing build. Install the tooling prerequisites from "
            "`tools/requirements.txt`, ensure a valid compile_commands.json "
            "is provided with --compile-db, or pass --skip-cross-module "
            "explicitly for a header-only local run.",
            file=sys.stderr,
        )
        return 2

    print(
        f"\nlint_timing_naming: {len(findings)} finding(s) — failing "
        "build. Suppress a single header-naming finding with a per-line "
        "comment like `// timing-naming-allow: <reason>`; a "
        "cross-module-read finding means a combinational-forward edge "
        "exists and must be fixed (stage the value through a REGISTERED "
        "pair) — it cannot be annotated away.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
